/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Don42 (https://sketchfab.com/Don42)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/d20-dice-w20-wurfel-3d-model-free-3b44541db43e4e979efec290ec706cbc
Title: D20 Dice (W20 Würfel) 3D model [FREE]
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function D20(props) {
  const { nodes, materials } = useGLTF('/models/d20_dice_w20_wurfel_3d_model_free.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere_Main_0.geometry}
          material={materials.Main}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere_Letters_0.geometry}
          material={materials.Letters}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/d20_dice_w20_wurfel_3d_model_free.glb')